// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJDtAMoS9WWbjDBx1Uy8yfRkxPZI3VqWI',
    appId: '1:609000800598:web:bee5af834d8b80ae20d6f7',
    messagingSenderId: '609000800598',
    projectId: 'hakocha-50413',
    authDomain: 'hakocha-50413.firebaseapp.com',
    storageBucket: 'hakocha-50413.firebasestorage.app',
    measurementId: 'G-T6TXVTXGSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJvTGUrwVfr99xqnoFZqnI6wBtetwmMoA',
    appId: '1:609000800598:android:1bdf4bbd7809f4ca20d6f7',
    messagingSenderId: '609000800598',
    projectId: 'hakocha-50413',
    storageBucket: 'hakocha-50413.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8bdeurdD24OlCtZNBrzSBndDHq83InEs',
    appId: '1:609000800598:ios:c90b25d30d8e344f20d6f7',
    messagingSenderId: '609000800598',
    projectId: 'hakocha-50413',
    storageBucket: 'hakocha-50413.firebasestorage.app',
    iosBundleId: 'com.example.hakocha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8bdeurdD24OlCtZNBrzSBndDHq83InEs',
    appId: '1:609000800598:ios:c90b25d30d8e344f20d6f7',
    messagingSenderId: '609000800598',
    projectId: 'hakocha-50413',
    storageBucket: 'hakocha-50413.firebasestorage.app',
    iosBundleId: 'com.example.hakocha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJDtAMoS9WWbjDBx1Uy8yfRkxPZI3VqWI',
    appId: '1:609000800598:web:22f9e94574ec297b20d6f7',
    messagingSenderId: '609000800598',
    projectId: 'hakocha-50413',
    authDomain: 'hakocha-50413.firebaseapp.com',
    storageBucket: 'hakocha-50413.firebasestorage.app',
    measurementId: 'G-32NWVGH1WR',
  );
}
